---
title: "MI Healthcare Dashboard 3"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}

library(flexdashboard)
library(kableExtra)
library(formattable)
library(readxl)
library(dplyr)
library(devtools)
library(shiny)

```



```{r, data, include=FALSE}

Region_1 <- read_excel("C:/Users/Alex Berge/OneDrive/Desktop/MI Healthcare Dashboard Project/Kable Sheets 2/Kable2 Region 1.xlsx", 
    col_types = c("text", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "text", "numeric", "numeric", 
        "numeric", "numeric"))

Region_2 <- read_excel("C:/Users/Alex Berge/OneDrive/Desktop/MI Healthcare Dashboard Project/Kable Sheets 2/Kable2 Region 2.xlsx", 
    col_types = c("text", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "text", "numeric", "numeric", 
        "numeric", "numeric"))

Region_3 <- read_excel("C:/Users/Alex Berge/OneDrive/Desktop/MI Healthcare Dashboard Project/Kable Sheets 2/Kable2 Region 3.xlsx", 
    col_types = c("text", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "text", "numeric", "numeric", 
        "numeric", "numeric"))

Region_4 <- read_excel("C:/Users/Alex Berge/OneDrive/Desktop/MI Healthcare Dashboard Project/Kable Sheets 2/Kable2 Region 4.xlsx", 
    col_types = c("text", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "text", "numeric", "numeric", 
        "numeric", "numeric"))

Region_5 <- read_excel("C:/Users/Alex Berge/OneDrive/Desktop/MI Healthcare Dashboard Project/Kable Sheets 2/Kable2 Region 5.xlsx", 
    col_types = c("text", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "text", "numeric", "numeric", 
        "numeric", "numeric"))

Region_6 <- read_excel("C:/Users/Alex Berge/OneDrive/Desktop/MI Healthcare Dashboard Project/Kable Sheets 2/Kable2 Region 6.xlsx", 
    col_types = c("text", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "text", "numeric", "numeric", 
        "numeric", "numeric"))

Region_7 <- read_excel("C:/Users/Alex Berge/OneDrive/Desktop/MI Healthcare Dashboard Project/Kable Sheets 2/Kable2 Region 7.xlsx", 
    col_types = c("text", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "text", "numeric", "numeric", 
        "numeric", "numeric"))
Region_8 <- read_excel("C:/Users/Alex Berge/OneDrive/Desktop/MI Healthcare Dashboard Project/Kable Sheets 2/Kable2 Region 8.xlsx", 
    col_types = c("text", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "text", "numeric", "numeric", 
        "numeric", "numeric"))

Region_9 <- read_excel("C:/Users/Alex Berge/OneDrive/Desktop/MI Healthcare Dashboard Project/Kable Sheets 2/Kable2 Region 9.xlsx", 
    col_types = c("text", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "text", "numeric", "numeric", 
        "numeric", "numeric"))

Region_10 <- read_excel("C:/Users/Alex Berge/OneDrive/Desktop/MI Healthcare Dashboard Project/Kable Sheets 2/Kable2 Region 10.xlsx", 
    col_types = c("text", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "text", "numeric", "numeric", 
        "numeric", "numeric"))

Statewide <- read_excel("C:/Users/Alex Berge/OneDrive/Desktop/MI Healthcare Dashboard Project/Kable Sheets 2/Kable2 Statewide.xlsx", 
    col_types = c("text", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "text", "numeric", "numeric", 
        "numeric", "numeric"))

```

```{r,  data cleaning continued, include=FALSE}

Region_1$`2022 - 2032 Openings` <- round(Region_1$`2022 - 2032 Openings`, 0)

Region_2$`2022 - 2032 Openings` <- round(Region_2$`2022 - 2032 Openings`, 0)

Region_3$`2022 - 2032 Openings` <- round(Region_3$`2022 - 2032 Openings`, 0)

Region_4$`2022 - 2032 Openings` <- round(Region_4$`2022 - 2032 Openings`, 0)

Region_5$`2022 - 2032 Openings` <- round(Region_5$`2022 - 2032 Openings`, 0)

Region_6$`2022 - 2032 Openings` <- round(Region_6$`2022 - 2032 Openings`, 0)

Region_7$`2022 - 2032 Openings` <- round(Region_7$`2022 - 2032 Openings`, 0)

Region_8$`2022 - 2032 Openings` <- round(Region_8$`2022 - 2032 Openings`, 0)

Region_9$`2022 - 2032 Openings` <- round(Region_9$`2022 - 2032 Openings`, 0)

Region_10$`2022 - 2032 Openings` <- round(Region_10$`2022 - 2032 Openings`, 0)

Statewide$`2022 - 2032 Openings` <- round(Statewide$`2022 - 2032 Openings`, 0)

```



```{r, the same deviled egg, include=FALSE}

Region_1$`Openings-Completions` <- round(Region_1$`Openings-Completions`, 0)

Region_2$`Openings-Completions` <- round(Region_2$`Openings-Completions`, 0)

Region_3$`Openings-Completions` <- round(Region_3$`Openings-Completions`, 0)

Region_4$`Openings-Completions` <- round(Region_4$`Openings-Completions`, 0)

Region_5$`Openings-Completions` <- round(Region_5$`Openings-Completions`, 0)

Region_6$`Openings-Completions` <- round(Region_6$`Openings-Completions`, 0)

Region_7$`Openings-Completions` <- round(Region_7$`Openings-Completions`, 0)

Region_8$`Openings-Completions` <- round(Region_8$`Openings-Completions`, 0)

Region_9$`Openings-Completions` <- round(Region_9$`Openings-Completions`, 0)

Region_10$`Openings-Completions` <- round(Region_10$`Openings-Completions`, 0)

Statewide$`Openings-Completions` <- round(Statewide$`Openings-Completions`, 0)

```



```{r, dollars, include=FALSE}

Region_1$`2021 Wage` <- currency(Region_1$`2021 Wage`)

Region_2$`2021 Wage` <- currency(Region_2$`2021 Wage`)

Region_3$`2021 Wage` <- currency(Region_3$`2021 Wage`)

Region_4$`2021 Wage` <- currency(Region_4$`2021 Wage`)

Region_5$`2021 Wage` <- currency(Region_5$`2021 Wage`)

Region_6$`2021 Wage` <- currency(Region_6$`2021 Wage`)

Region_7$`2021 Wage` <- currency(Region_7$`2021 Wage`)

Region_8$`2021 Wage` <- currency(Region_8$`2021 Wage`)

Region_9$`2021 Wage` <- currency(Region_9$`2021 Wage`)

Region_10$`2021 Wage` <- currency(Region_10$`2021 Wage`)

Statewide$`2021 Wage` <- currency(Statewide$`2021 Wage`)

```



```{r, almost the final cleaning, include=FALSE}

Region_1$`2017 Wage` <- currency(Region_1$`2017 Wage`)

Region_2$`2017 Wage` <- currency(Region_2$`2017 Wage`)

Region_3$`2017 Wage` <- currency(Region_3$`2017 Wage`)

Region_4$`2017 Wage` <- currency(Region_4$`2017 Wage`)

Region_5$`2017 Wage` <- currency(Region_5$`2017 Wage`)

Region_6$`2017 Wage` <- currency(Region_6$`2017 Wage`)

Region_7$`2017 Wage` <- currency(Region_7$`2017 Wage`)

Region_8$`2017 Wage` <- currency(Region_8$`2017 Wage`)

Region_9$`2017 Wage` <- currency(Region_9$`2017 Wage`)

Region_10$`2017 Wage` <- currency(Region_10$`2017 Wage`)

Statewide$`2017 Wage` <- currency(Statewide$`2017 Wage`)

```



```{r, now the final cleaning, include=FALSE}

Region_1$`Wage Growth per hour 2017-2021` <- currency(Region_1$`Wage Growth per hour 2017-2021`)

Region_2$`Wage Growth per hour 2017-2021` <- currency(Region_2$`Wage Growth per hour 2017-2021`)

Region_3$`Wage Growth per hour 2017-2021` <- currency(Region_3$`Wage Growth per hour 2017-2021`)

Region_4$`Wage Growth per hour 2017-2021` <- currency(Region_4$`Wage Growth per hour 2017-2021`)

Region_5$`Wage Growth per hour 2017-2021` <- currency(Region_5$`Wage Growth per hour 2017-2021`)

Region_6$`Wage Growth per hour 2017-2021` <- currency(Region_6$`Wage Growth per hour 2017-2021`)

Region_7$`Wage Growth per hour 2017-2021` <- currency(Region_7$`Wage Growth per hour 2017-2021`)

Region_8$`Wage Growth per hour 2017-2021` <- currency(Region_8$`Wage Growth per hour 2017-2021`)

Region_9$`Wage Growth per hour 2017-2021` <- currency(Region_9$`Wage Growth per hour 2017-2021`)

Region_10$`Wage Growth per hour 2017-2021` <- currency(Region_10$`Wage Growth per hour 2017-2021`)

Statewide$`Wage Growth per hour 2017-2021` <- currency(Statewide$`Wage Growth per hour 2017-2021`)

```



```{r, Region 1 Percentage Formatting, include=FALSE}

Region_1$`2022 Turnover Rate` <- formattable::percent(Region_1$`2022 Turnover Rate`, digits = 0)

  Region_1$`2022 - 2032 % Change` <- formattable::percent(Region_1$`2022 - 2032 % Change`, digits = 0)
    
    Region_1$`Percentage Growth` <- formattable::percent(Region_1$`Percentage Growth`, digits = 2)
  
```



```{r, Region 2 Percentage Formatting, include=FALSE}

Region_2$`2022 Turnover Rate` <- formattable::percent(Region_2$`2022 Turnover Rate`, digits = 0)

  Region_2$`2022 - 2032 % Change` <- formattable::percent(Region_2$`2022 - 2032 % Change`, digits = 0)
    
    Region_2$`Percentage Growth` <- formattable::percent(Region_2$`Percentage Growth`, digits = 2)
  
```



```{r, Region 3 Percentage Formatting, include=FALSE}

Region_3$`2022 Turnover Rate` <- formattable::percent(Region_3$`2022 Turnover Rate`, digits = 0)

  Region_3$`2022 - 2032 % Change` <- formattable::percent(Region_3$`2022 - 2032 % Change`, digits = 0)
    
    Region_3$`Percentage Growth` <- formattable::percent(Region_3$`Percentage Growth`, digits = 2)
  
```



```{r, Region 4 Percentage Formatting, include=FALSE}

Region_4$`2022 Turnover Rate` <- formattable::percent(Region_4$`2022 Turnover Rate`, digits = 0)

  Region_4$`2022 - 2032 % Change` <- formattable::percent(Region_4$`2022 - 2032 % Change`, digits = 0)
    
    Region_4$`Percentage Growth` <- formattable::percent(Region_4$`Percentage Growth`, digits = 2)
  
```



```{r, Region 5 Percentage Formatting, include=FALSE}

Region_5$`2022 Turnover Rate` <- formattable::percent(Region_5$`2022 Turnover Rate`, digits = 0)

  Region_5$`2022 - 2032 % Change` <- formattable::percent(Region_5$`2022 - 2032 % Change`, digits = 0)
    
    Region_5$`Percentage Growth` <- formattable::percent(Region_5$`Percentage Growth`, digits = 2)
  
```



```{r, Region 6 Percentage Formatting, include=FALSE}

Region_6$`2022 Turnover Rate` <- formattable::percent(Region_6$`2022 Turnover Rate`, digits = 0)

  Region_6$`2022 - 2032 % Change` <- formattable::percent(Region_6$`2022 - 2032 % Change`, digits = 0)
    
    Region_6$`Percentage Growth` <- formattable::percent(Region_6$`Percentage Growth`, digits = 2)
  
```



```{r, Region 7 Percentage Formatting, include=FALSE}

Region_7$`2022 Turnover Rate` <- formattable::percent(Region_7$`2022 Turnover Rate`, digits = 0)

  Region_7$`2022 - 2032 % Change` <- formattable::percent(Region_7$`2022 - 2032 % Change`, digits = 0)
    
    Region_7$`Percentage Growth` <- formattable::percent(Region_7$`Percentage Growth`, digits = 2)
  
```



```{r, Region 8 Percentage Formatting, include=FALSE}

Region_8$`2022 Turnover Rate` <- formattable::percent(Region_8$`2022 Turnover Rate`, digits = 0)

  Region_8$`2022 - 2032 % Change` <- formattable::percent(Region_8$`2022 - 2032 % Change`, digits = 0)
    
    Region_8$`Percentage Growth` <- formattable::percent(Region_8$`Percentage Growth`, digits = 2)
  
```



```{r, Region 9 Percentage Formatting, include=FALSE}

Region_9$`2022 Turnover Rate` <- formattable::percent(Region_9$`2022 Turnover Rate`, digits = 0)

  Region_9$`2022 - 2032 % Change` <- formattable::percent(Region_9$`2022 - 2032 % Change`, digits = 0)
    
    Region_9$`Percentage Growth` <- formattable::percent(Region_9$`Percentage Growth`, digits = 2)
  
```



```{r, Region 10 Percentage Formatting, include=FALSE}

Region_10$`2022 Turnover Rate` <- formattable::percent(Region_10$`2022 Turnover Rate`, digits = 0)

  Region_10$`2022 - 2032 % Change` <- formattable::percent(Region_10$`2022 - 2032 % Change`, digits = 0)
    
    Region_10$`Percentage Growth` <- formattable::percent(Region_10$`Percentage Growth`, digits = 2)
  
```



```{r, Region Statewide Percentage Formatting, include=FALSE}

Statewide$`2022 Turnover Rate` <- formattable::percent(Statewide$`2022 Turnover Rate`, digits = 0)

  Statewide$`2022 - 2032 % Change` <- formattable::percent(Statewide$`2022 - 2032 % Change`, digits = 0)
    
    Statewide$`Percentage Growth` <- formattable::percent(Statewide$`Percentage Growth`, digits = 2)
  
```



```{r, New Variables Time, include=FALSE}

#Region_1["Percentage Growth"][is.na(Region_1["Percentage Growth"])] <- 0

#sum(is.na(Region_1$`Percentage Growth`)) 

 
#R1 <- mutate(Region_1, "Percent Change" = cell_spec(`Percentage Growth`, color = ifelse(`Percentage Growth` > 0, "green","red")))



```



Regional Trends {data-width=650}
-----------------------------------------------------------------------

# Statewide Data
```{r, Statewide, include=TRUE}

S1 <- kbl(Statewide, align = "lccccccccccc") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), fixed_thead = T) %>%
  column_spec(1,width = "30em") %>%
  column_spec(12, color = case_when(Statewide$`Percentage Growth` > 0 ~ 'green', 
                                    Statewide$`Percentage Growth` < 0 ~ 'red', 
                                    is.na(Statewide$`Percentage Growth`) ~ 'black', 
                                    TRUE ~ 'black')) %>% 
  column_spec(3, color = case_when(Statewide$`2022 - 2032 % Change` > 0 ~ 'green', 
                                    Statewide$`2022 - 2032 % Change` < 0 ~ 'red', 
                                    is.na(Statewide$`2022 - 2032 % Change`) ~ 'black', 
                                    TRUE ~ 'black')) %>%
  column_spec(7, bold = T, color = case_when(Statewide$`Openings-Completions` < 0 ~ 'green', 
                                    Statewide$`Openings-Completions` > 0 ~ 'red', 
                                    is.na(Statewide$`Openings-Completions`) ~ 'black', 
                                    TRUE ~ 'black')) %>%
  row_spec(8, bold = T) %>%
  row_spec(11, bold = T) %>%
  row_spec(15, bold = T) %>%
  row_spec(25, bold = T) %>%
  row_spec(31, bold = T) %>%
  row_spec(36, bold = T) %>%
  row_spec(40, bold = T) %>%
  row_spec(44, bold = T) %>%
  row_spec(51, bold = T) %>%
  add_indent(3:8) %>%
  pack_rows("Behavioral Group", 1, 11) %>%
  pack_rows("Dentistry Group", 12, 15) %>%
  pack_rows("Medical Technicians Group", 16, 25) %>%
  pack_rows("Nursing Group", 26, 31) %>%
  pack_rows("Patient Support Group", 32, 36) %>%
  pack_rows("Pharmacy Group", 37, 40) %>%
  pack_rows("Physician Group", 41, 44) %>%
  pack_rows("Therapy Group", 45, 51)

S1

```


# Region 1 {data-navmenu="Regions"}
```{r, Region 1 Kable Formatting, include=TRUE}

R1 <-kbl(Region_1, align = "lcccccccccccccc") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), fixed_thead = T) %>%
  column_spec(1,width = "30em") %>%
  column_spec(12, color = case_when(Region_1$`Percentage Growth` > 0 ~ 'green', 
                                    Region_1$`Percentage Growth` < 0 ~ 'red', 
                                    is.na(Region_1$`Percentage Growth`) ~ 'black', 
                                    TRUE ~ 'black')) %>% 
  column_spec(3, color = case_when(Region_1$`2022 - 2032 % Change` > 0 ~ 'green', 
                                    Region_1$`2022 - 2032 % Change` < 0 ~ 'red', 
                                    is.na(Region_1$`2022 - 2032 % Change`) ~ 'black', 
                                    TRUE ~ 'black')) %>%
  column_spec(7, bold = T, color = case_when(Region_1$`Openings-Completions` < 0 ~ 'green', 
                                    Region_1$`Openings-Completions` > 0 ~ 'red', 
                                    is.na(Region_1$`Openings-Completions`) ~ 'black', 
                                    TRUE ~ 'black')) %>%  
  row_spec(8, bold = T) %>%
  row_spec(11, bold = T) %>%
  row_spec(15, bold = T) %>%
  row_spec(25, bold = T) %>%
  row_spec(31, bold = T) %>%
  row_spec(36, bold = T) %>%
  row_spec(40, bold = T) %>%
  row_spec(44, bold = T) %>%
  row_spec(51, bold = T) %>%
  add_indent(3:8) %>%
  pack_rows("Behavioral Group", 1, 11) %>%
  pack_rows("Dentistry Group", 12, 15) %>%
  pack_rows("Medical Technicians Group", 16, 25) %>%
  pack_rows("Nursing Group", 26, 31) %>%
  pack_rows("Patient Support Group", 32, 36) %>%
  pack_rows("Pharmacy Group", 37, 40) %>%
  pack_rows("Physician Group", 41, 44) %>%
  pack_rows("Therapy Group", 45, 51)

R1

```



# Region 2 {data-navmenu="Regions"}
```{r, Region 2, include=TRUE}

R2 <- kbl(Region_2, align = "lcccccccccccccc") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), fixed_thead = T) %>%
  column_spec(1,width = "30em") %>%
  column_spec(12, color = case_when(Region_2$`Percentage Growth` > 0 ~ 'green', 
                                    Region_2$`Percentage Growth` < 0 ~ 'red', 
                                    is.na(Region_2$`Percentage Growth`) ~ 'black', 
                                    TRUE ~ 'black')) %>% 
  column_spec(3, color = case_when(Region_2$`2022 - 2032 % Change` > 0 ~ 'green', 
                                    Region_2$`2022 - 2032 % Change` < 0 ~ 'red', 
                                    is.na(Region_2$`2022 - 2032 % Change`) ~ 'black', 
                                    TRUE ~ 'black')) %>%
  column_spec(7, bold = T, color = case_when(Region_2$`Openings-Completions` < 0 ~ 'green', 
                                    Region_2$`Openings-Completions` > 0 ~ 'red', 
                                    is.na(Region_2$`Openings-Completions`) ~ 'black', 
                                    TRUE ~ 'black')) %>% 
  row_spec(8, bold = T) %>%
  row_spec(11, bold = T) %>%
  row_spec(15, bold = T) %>%
  row_spec(25, bold = T) %>%
  row_spec(31, bold = T) %>%
  row_spec(36, bold = T) %>%
  row_spec(40, bold = T) %>%
  row_spec(44, bold = T) %>%
  row_spec(51, bold = T) %>%
  add_indent(3:8) %>%
  pack_rows("Behavioral Group", 1, 11) %>%
  pack_rows("Dentistry Group", 12, 15) %>%
  pack_rows("Medical Technicians Group", 16, 25) %>%
  pack_rows("Nursing Group", 26, 31) %>%
  pack_rows("Patient Support Group", 32, 36) %>%
  pack_rows("Pharmacy Group", 37, 40) %>%
  pack_rows("Physician Group", 41, 44) %>%
  pack_rows("Therapy Group", 45, 51)

R2

```



# Region 3 {data-navmenu="Regions"}
```{r, Region 3, include=TRUE}

R3 <- kbl(Region_3, align = "lcccccccccccccc") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), fixed_thead = T) %>%
  column_spec(1,width = "30em") %>%
  column_spec(12, color = case_when(Region_3$`Percentage Growth` > 0 ~ 'green', 
                                    Region_3$`Percentage Growth` < 0 ~ 'red', 
                                    is.na(Region_3$`Percentage Growth`) ~ 'black', 
                                    TRUE ~ 'black')) %>% 
  column_spec(3, color = case_when(Region_3$`2022 - 2032 % Change` > 0 ~ 'green', 
                                    Region_3$`2022 - 2032 % Change` < 0 ~ 'red', 
                                    is.na(Region_3$`2022 - 2032 % Change`) ~ 'black', 
                                    TRUE ~ 'black')) %>%
  column_spec(7, bold = T, color = case_when(Region_3$`Openings-Completions` < 0 ~ 'green', 
                                    Region_3$`Openings-Completions` > 0 ~ 'red', 
                                    is.na(Region_3$`Openings-Completions`) ~ 'black', 
                                    TRUE ~ 'black')) %>% 
  row_spec(8, bold = T) %>%
  row_spec(11, bold = T) %>%
  row_spec(15, bold = T) %>%
  row_spec(25, bold = T) %>%
  row_spec(31, bold = T) %>%
  row_spec(36, bold = T) %>%
  row_spec(40, bold = T) %>%
  row_spec(44, bold = T) %>%
  row_spec(51, bold = T) %>%
  add_indent(3:8) %>%
  pack_rows("Behavioral Group", 1, 11) %>%
  pack_rows("Dentistry Group", 12, 15) %>%
  pack_rows("Medical Technicians Group", 16, 25) %>%
  pack_rows("Nursing Group", 26, 31) %>%
  pack_rows("Patient Support Group", 32, 36) %>%
  pack_rows("Pharmacy Group", 37, 40) %>%
  pack_rows("Physician Group", 41, 44) %>%
  pack_rows("Therapy Group", 45, 51)

R3

```



# Region 4 {data-navmenu="Regions"}
```{r, Region 4, include=TRUE}

R4 <- kbl(Region_4, align = "lcccccccccccccc") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), fixed_thead = T) %>%
  column_spec(1,width = "30em") %>%
  column_spec(12, color = case_when(Region_4$`Percentage Growth` > 0 ~ 'green', 
                                    Region_4$`Percentage Growth` < 0 ~ 'red', 
                                    is.na(Region_4$`Percentage Growth`) ~ 'black', 
                                    TRUE ~ 'black')) %>% 
  column_spec(3, color = case_when(Region_4$`2022 - 2032 % Change` > 0 ~ 'green', 
                                    Region_4$`2022 - 2032 % Change` < 0 ~ 'red', 
                                    is.na(Region_4$`2022 - 2032 % Change`) ~ 'black', 
                                    TRUE ~ 'black')) %>%
  column_spec(7, bold = T, color = case_when(Region_4$`Openings-Completions` < 0 ~ 'green', 
                                    Region_4$`Openings-Completions` > 0 ~ 'red', 
                                    is.na(Region_4$`Openings-Completions`) ~ 'black', 
                                    TRUE ~ 'black')) %>% 
  row_spec(8, bold = T) %>%
  row_spec(11, bold = T) %>%
  row_spec(15, bold = T) %>%
  row_spec(25, bold = T) %>%
  row_spec(31, bold = T) %>%
  row_spec(36, bold = T) %>%
  row_spec(40, bold = T) %>%
  row_spec(44, bold = T) %>%
  row_spec(51, bold = T) %>%
  add_indent(3:8) %>%
  pack_rows("Behavioral Group", 1, 11) %>%
  pack_rows("Dentistry Group", 12, 15) %>%
  pack_rows("Medical Technicians Group", 16, 25) %>%
  pack_rows("Nursing Group", 26, 31) %>%
  pack_rows("Patient Support Group", 32, 36) %>%
  pack_rows("Pharmacy Group", 37, 40) %>%
  pack_rows("Physician Group", 41, 44) %>%
  pack_rows("Therapy Group", 45, 51)

R4

```



# Region 5 {data-navmenu="Regions"}
```{r, Region 5, include=TRUE}

R5 <- kbl(Region_5, align = "lcccccccccccccc") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), fixed_thead = T) %>%
  column_spec(1,width = "30em") %>%
  column_spec(12, color = case_when(Region_5$`Percentage Growth` > 0 ~ 'green', 
                                    Region_5$`Percentage Growth` < 0 ~ 'red', 
                                    is.na(Region_5$`Percentage Growth`) ~ 'black', 
                                    TRUE ~ 'black')) %>% 
  column_spec(3, color = case_when(Region_5$`2022 - 2032 % Change` > 0 ~ 'green', 
                                    Region_5$`2022 - 2032 % Change` < 0 ~ 'red', 
                                    is.na(Region_5$`2022 - 2032 % Change`) ~ 'black', 
                                    TRUE ~ 'black')) %>%
  column_spec(7, bold = T, color = case_when(Region_5$`Openings-Completions` < 0 ~ 'green', 
                                    Region_5$`Openings-Completions` > 0 ~ 'red', 
                                    is.na(Region_5$`Openings-Completions`) ~ 'black', 
                                    TRUE ~ 'black')) %>% 
  row_spec(8, bold = T) %>%
  row_spec(11, bold = T) %>%
  row_spec(15, bold = T) %>%
  row_spec(25, bold = T) %>%
  row_spec(31, bold = T) %>%
  row_spec(36, bold = T) %>%
  row_spec(40, bold = T) %>%
  row_spec(44, bold = T) %>%
  row_spec(51, bold = T) %>%
  add_indent(3:8) %>%
  pack_rows("Behavioral Group", 1, 11) %>%
  pack_rows("Dentistry Group", 12, 15) %>%
  pack_rows("Medical Technicians Group", 16, 25) %>%
  pack_rows("Nursing Group", 26, 31) %>%
  pack_rows("Patient Support Group", 32, 36) %>%
  pack_rows("Pharmacy Group", 37, 40) %>%
  pack_rows("Physician Group", 41, 44) %>%
  pack_rows("Therapy Group", 45, 51)

R5

```



# Region 6 {data-navmenu="Regions"}
```{r, Region 6, include=TRUE}

R6 <- kbl(Region_6, align = "lcccccccccccccc") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), fixed_thead = T) %>%
  column_spec(1,width = "30em") %>%
  column_spec(12, color = case_when(Region_6$`Percentage Growth` > 0 ~ 'green', 
                                    Region_6$`Percentage Growth` < 0 ~ 'red', 
                                    is.na(Region_6$`Percentage Growth`) ~ 'black', 
                                    TRUE ~ 'black')) %>% 
  column_spec(3, color = case_when(Region_6$`2022 - 2032 % Change` > 0 ~ 'green', 
                                    Region_6$`2022 - 2032 % Change` < 0 ~ 'red', 
                                    is.na(Region_6$`2022 - 2032 % Change`) ~ 'black', 
                                    TRUE ~ 'black')) %>%
  column_spec(7, bold = T, color = case_when(Region_6$`Openings-Completions` < 0 ~ 'green', 
                                    Region_6$`Openings-Completions` > 0 ~ 'red', 
                                    is.na(Region_6$`Openings-Completions`) ~ 'black', 
                                    TRUE ~ 'black')) %>% 
  row_spec(8, bold = T) %>%
  row_spec(11, bold = T) %>%
  row_spec(15, bold = T) %>%
  row_spec(25, bold = T) %>%
  row_spec(31, bold = T) %>%
  row_spec(36, bold = T) %>%
  row_spec(40, bold = T) %>%
  row_spec(44, bold = T) %>%
  row_spec(51, bold = T) %>%
  add_indent(3:8) %>%
  pack_rows("Behavioral Group", 1, 11) %>%
  pack_rows("Dentistry Group", 12, 15) %>%
  pack_rows("Medical Technicians Group", 16, 25) %>%
  pack_rows("Nursing Group", 26, 31) %>%
  pack_rows("Patient Support Group", 32, 36) %>%
  pack_rows("Pharmacy Group", 37, 40) %>%
  pack_rows("Physician Group", 41, 44) %>%
  pack_rows("Therapy Group", 45, 51)

R6

```



# Region 7 {data-navmenu="Regions"}
```{r, Region 7, include=TRUE}

R7 <- kbl(Region_7, align = "lcccccccccccccc") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), fixed_thead = T) %>%
  column_spec(1,width = "30em") %>%
  column_spec(12, color = case_when(Region_7$`Percentage Growth` > 0 ~ 'green', 
                                    Region_7$`Percentage Growth` < 0 ~ 'red', 
                                    is.na(Region_7$`Percentage Growth`) ~ 'black', 
                                    TRUE ~ 'black')) %>% 
  column_spec(3, color = case_when(Region_7$`2022 - 2032 % Change` > 0 ~ 'green', 
                                    Region_7$`2022 - 2032 % Change` < 0 ~ 'red', 
                                    is.na(Region_7$`2022 - 2032 % Change`) ~ 'black', 
                                    TRUE ~ 'black')) %>%
  column_spec(7, bold = T, color = case_when(Region_7$`Openings-Completions` < 0 ~ 'green', 
                                    Region_7$`Openings-Completions` > 0 ~ 'red', 
                                    is.na(Region_7$`Openings-Completions`) ~ 'black', 
                                    TRUE ~ 'black')) %>% 
  row_spec(8, bold = T) %>%
  row_spec(11, bold = T) %>%
  row_spec(15, bold = T) %>%
  row_spec(25, bold = T) %>%
  row_spec(31, bold = T) %>%
  row_spec(36, bold = T) %>%
  row_spec(40, bold = T) %>%
  row_spec(44, bold = T) %>%
  row_spec(51, bold = T) %>%
  add_indent(3:8) %>%
  pack_rows("Behavioral Group", 1, 11) %>%
  pack_rows("Dentistry Group", 12, 15) %>%
  pack_rows("Medical Technicians Group", 16, 25) %>%
  pack_rows("Nursing Group", 26, 31) %>%
  pack_rows("Patient Support Group", 32, 36) %>%
  pack_rows("Pharmacy Group", 37, 40) %>%
  pack_rows("Physician Group", 41, 44) %>%
  pack_rows("Therapy Group", 45, 51)

R7

```




# Region 8 {data-navmenu="Regions"}
```{r, Region 8, include=TRUE}

R8 <- kbl(Region_8, align = "lcccccccccccccc") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), fixed_thead = T) %>%
  column_spec(1,width = "30em") %>%
  column_spec(12, color = case_when(Region_8$`Percentage Growth` > 0 ~ 'green', 
                                    Region_8$`Percentage Growth` < 0 ~ 'red', 
                                    is.na(Region_8$`Percentage Growth`) ~ 'black', 
                                    TRUE ~ 'black')) %>% 
  column_spec(3, color = case_when(Region_8$`2022 - 2032 % Change` > 0 ~ 'green', 
                                    Region_8$`2022 - 2032 % Change` < 0 ~ 'red', 
                                    is.na(Region_8$`2022 - 2032 % Change`) ~ 'black', 
                                    TRUE ~ 'black')) %>%
  column_spec(7, bold = T, color = case_when(Region_8$`Openings-Completions` < 0 ~ 'green', 
                                    Region_8$`Openings-Completions` > 0 ~ 'red', 
                                    is.na(Region_8$`Openings-Completions`) ~ 'black', 
                                    TRUE ~ 'black')) %>% 
  row_spec(8, bold = T) %>%
  row_spec(11, bold = T) %>%
  row_spec(15, bold = T) %>%
  row_spec(25, bold = T) %>%
  row_spec(31, bold = T) %>%
  row_spec(36, bold = T) %>%
  row_spec(40, bold = T) %>%
  row_spec(44, bold = T) %>%
  row_spec(51, bold = T) %>%
  add_indent(3:8) %>%
  pack_rows("Behavioral Group", 1, 11) %>%
  pack_rows("Dentistry Group", 12, 15) %>%
  pack_rows("Medical Technicians Group", 16, 25) %>%
  pack_rows("Nursing Group", 26, 31) %>%
  pack_rows("Patient Support Group", 32, 36) %>%
  pack_rows("Pharmacy Group", 37, 40) %>%
  pack_rows("Physician Group", 41, 44) %>%
  pack_rows("Therapy Group", 45, 51)

R8

```



# Region 9 {data-navmenu="Regions"}
```{r, Region 9, include=TRUE}

R9 <- kbl(Region_9, align = "lcccccccccccccc") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), fixed_thead = T) %>%
  column_spec(1,width = "30em") %>%
    column_spec(12, color = case_when(Region_9$`Percentage Growth` > 0 ~ 'green', 
                                    Region_9$`Percentage Growth` < 0 ~ 'red', 
                                    is.na(Region_9$`Percentage Growth`) ~ 'black', 
                                    TRUE ~ 'black')) %>% 
  column_spec(3, color = case_when(Region_9$`2022 - 2032 % Change` > 0 ~ 'green', 
                                    Region_9$`2022 - 2032 % Change` < 0 ~ 'red', 
                                    is.na(Region_9$`2022 - 2032 % Change`) ~ 'black', 
                                    TRUE ~ 'black')) %>%
  column_spec(7, bold = T, color = case_when(Region_9$`Openings-Completions` < 0 ~ 'green', 
                                    Region_9$`Openings-Completions` > 0 ~ 'red', 
                                    is.na(Region_9$`Openings-Completions`) ~ 'black', 
                                    TRUE ~ 'black')) %>% 
  row_spec(8, bold = T) %>%
  row_spec(11, bold = T) %>%
  row_spec(15, bold = T) %>%
  row_spec(25, bold = T) %>%
  row_spec(31, bold = T) %>%
  row_spec(36, bold = T) %>%
  row_spec(40, bold = T) %>%
  row_spec(44, bold = T) %>%
  row_spec(51, bold = T) %>%
  add_indent(3:8) %>%
  pack_rows("Behavioral Group", 1, 11) %>%
  pack_rows("Dentistry Group", 12, 15) %>%
  pack_rows("Medical Technicians Group", 16, 25) %>%
  pack_rows("Nursing Group", 26, 31) %>%
  pack_rows("Patient Support Group", 32, 36) %>%
  pack_rows("Pharmacy Group", 37, 40) %>%
  pack_rows("Physician Group", 41, 44) %>%
  pack_rows("Therapy Group", 45, 51)

R9

```




# Region 10 {data-navmenu="Regions"}
```{r, Region 10, include=TRUE}

R10 <- kbl(Region_10, align = "lcccccccccccccc") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), fixed_thead = T) %>%
  column_spec(1,width = "30em") %>%
  column_spec(12, color = case_when(Region_10$`Percentage Growth` > 0 ~ 'green', 
                                    Region_10$`Percentage Growth` < 0 ~ 'red', 
                                    is.na(Region_10$`Percentage Growth`) ~ 'black', 
                                    TRUE ~ 'black')) %>% 
  column_spec(3, color = case_when(Region_10$`2022 - 2032 % Change` > 0 ~ 'green', 
                                    Region_10$`2022 - 2032 % Change` < 0 ~ 'red', 
                                    is.na(Region_10$`2022 - 2032 % Change`) ~ 'black', 
                                    TRUE ~ 'black')) %>%
  column_spec(7, bold = T, color = case_when(Region_10$`Openings-Completions` < 0 ~ 'green', 
                                    Region_10$`Openings-Completions` > 0 ~ 'red', 
                                    is.na(Region_10$`Openings-Completions`) ~ 'black', 
                                    TRUE ~ 'black')) %>% 
  row_spec(8, bold = T) %>%
  row_spec(11, bold = T) %>%
  row_spec(15, bold = T) %>%
  row_spec(25, bold = T) %>%
  row_spec(31, bold = T) %>%
  row_spec(36, bold = T) %>%
  row_spec(40, bold = T) %>%
  row_spec(44, bold = T) %>%
  row_spec(51, bold = T) %>%
  add_indent(3:8) %>%
  pack_rows("Behavioral Group", 1, 11) %>%
  pack_rows("Dentistry Group", 12, 15) %>%
  pack_rows("Medical Technicians Group", 16, 25) %>%
  pack_rows("Nursing Group", 26, 31) %>%
  pack_rows("Patient Support Group", 32, 36) %>%
  pack_rows("Pharmacy Group", 37, 40) %>%
  pack_rows("Physician Group", 41, 44) %>%
  pack_rows("Therapy Group", 45, 51)

R10

```
